# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
default-template: haskeleton
templates: 
  scm-init: git
  params:
    author-name: Remo Giermann
    author-email: mo@liberejo.de
    copyright: (c) Remo Giermann
    github-username: modul
    category: Experimental

local-bin-path: /home/mo/bin/

build:
    haddock-arguments: 
        haddock-args:
            - "--odir=docs"
    haddock-deps: false
