"
" usual options
" 
syntax on
set nocompatible
set ts=2 sts=2 sw=2 sr
set autoindent expandtab 
set incsearch nowrap nu modeline autoread
set guioptions=agi
set spelllang=de
set undofile
set undodir=~/.vim/undodir
set mouse=a
set hidden " required for CtrlSpace
set re=2

" 
" Vundle plugin management
"
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" plugin on GitHub repo: 'user/repo'
" plugin from http://vim-scripts.org/vim/scripts.html: 'name'
" plugin via any git: 'git://path/to/repo.git'
" plugin on local machine: 'file:///path/to/plugin'
" more options and examples on github.com/VundleVim/Vundle.vim

Plugin 'VundleVim/Vundle.vim'	    	" vundle itself
Plugin 'jacoborus/tender.vim'       " color scheme
Plugin 'tpope/vim-commentary'		    " commenting
Plugin 'kien/ctrlp.vim'             " Fuzzy Finder
Plugin 'easymotion/vim-easymotion'  " motion helper and highlighter
Plugin 'vim-airline/vim-airline'	  " status line
Plugin 'dag/vim-fish'               " syntax highlighting for fish

call vundle#end()
filetype plugin indent on

map <f4> :bo term<CR>

set background=dark
colorscheme tender

" let g:ctrlp_map = '<f1>'

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

"
" jump to last cursor position when opening files
" 
function! ResCur()
	if line("'\"") <= line("$")
		normal! g`"
		return 1
	endif
endfunction

augroup resCur
	autocmd!
	autocmd BufWinEnter * call ResCur()
augroup END
" -------------------------------------------
